version: "3.8"

services:
  # 🗄️ Database (persistent volume)
  db:
    image: postgres:15
    container_name: wifi_postgres
    restart: always
    environment:
      POSTGRES_USER: wifi_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: wifi_billing
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  # ⚙️ Backend API (Node.js)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wifi_backend
    restart: always
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=wifi_user
      - DB_PASS=password123
      - DB_NAME=wifi_billing
    depends_on:
      - db
    expose:
      - "5000"

  # 🌐 Frontend (React, built for production)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wifi_frontend
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    expose:
      - "80"

  # 🚦 NGINX reverse proxy
  nginx:
    image: nginx:latest
    container_name: wifi_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
