#!/bin/bash

# Access Point Configuration Helper
# Generates configuration for different AP types

GATEWAY_IP=${1:-"192.168.182.1"}
SAAS_URL=${2:-"https://your-saas.com"}
UAM_PORT=${3:-"3990"}

echo "🌐 Access Point Configuration Guide"
echo "Gateway IP: ${GATEWAY_IP}"
echo "SaaS URL: ${SAAS_URL}"
echo "UAM Port: ${UAM_PORT}"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "📡 Ubiquiti/UniFi Configuration"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. Network Settings:"
echo "   - Gateway: ${GATEWAY_IP}"
echo "   - DNS: 8.8.8.8, 8.8.4.4"
echo "   - Subnet: 192.168.182.0/24"
echo ""
echo "2. Guest Portal Settings:"
echo "   - Enable Guest Portal: Yes"
echo "   - Portal URL: http://${GATEWAY_IP}:${UAM_PORT}"
echo "   - Redirect URL: ${SAAS_URL}/portal"
echo ""
echo "3. Wireless Network:"
echo "   - Create new SSID"
echo "   - Enable Guest Policy"
echo "   - Assign to Hotspot network"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "📡 Generic Access Point Configuration"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "DHCP Settings:"
echo "  - Disable DHCP on AP"
echo "  - Gateway: ${GATEWAY_IP}"
echo "  - DNS: 8.8.8.8, 8.8.4.4"
echo ""
echo "Captive Portal Settings:"
echo "  - Enable Captive Portal: Yes"
echo "  - Portal URL: http://${GATEWAY_IP}:${UAM_PORT}"
echo "  - Redirect URL: ${SAAS_URL}/portal"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "📡 MikroTik Router Configuration"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Via Winbox or CLI:"
echo ""
echo "/ip hotspot profile set default html-directory=\"/hotspot\""
echo "/ip hotspot set [find] html-directory=\"/hotspot\""
echo "/ip route add dst-address=0.0.0.0/0 gateway=${GATEWAY_IP}"
echo ""
echo "Hotspot Settings:"
echo "  - Gateway: ${GATEWAY_IP}"
echo "  - DNS: 8.8.8.8"
echo "  - Portal URL: http://${GATEWAY_IP}:${UAM_PORT}"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "📡 OpenWrt Configuration"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Network Configuration (/etc/config/network):"
echo ""
echo "config interface 'hotspot'"
echo "    option proto 'static'"
echo "    option ipaddr '${GATEWAY_IP}'"
echo "    option netmask '255.255.255.0'"
echo "    option gateway '${GATEWAY_IP}'"
echo "    list dns '8.8.8.8'"
echo "    list dns '8.8.4.4'"
echo ""
echo "Captive Portal:"
echo "  - Install nodogsplash or coova-chilli"
echo "  - Configure gateway: ${GATEWAY_IP}"
echo "  - Portal URL: http://${GATEWAY_IP}:${UAM_PORT}"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "✅ Configuration Complete"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "After configuration:"
echo "  1. Test connectivity: ping ${GATEWAY_IP}"
echo "  2. Test portal: curl http://${GATEWAY_IP}:${UAM_PORT}"
echo "  3. Connect device and verify redirect"
echo ""

